#!/usr/bin/env bash
function gradle_check() {
    local TASK=$1
    echo "Running check: $TASK..."
    # shellcheck disable=SC2155
    local OUTPUT="/tmp/$TASK-$(date +%s)"
    ./gradlew "$TASK" &> "$OUTPUT" 
    EXIT_CODE=$?
    if [ $EXIT_CODE -ne 0 ]; then
      cat "$OUTPUT"
      rm "$OUTPUT"
      echo >&2 "$TASK failed!"
      exit $EXIT_CODE
    fi
    rm "$OUTPUT"
}

for check in spotlessKotlinCheck detekt lint; do
    gradle_check "$check"
done
